version: '3'

services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'verifymy-api'
      MYSQL_USER: 'verifymy'
      MYSQL_PASSWORD: 'v3r1fymy-p455w0rd'
      MYSQL_ROOT_PASSWORD: 'ni12y312ut321n3li21u3o21'
    expose:
      - '3306'
    ports:
      - '3306:3306'
    volumes:
      - ./storage/data/:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspace
    ports:
      - 6073:8080
    depends_on:
      - database
    links:
      - database
